# Generated by Django 2.0.6 on 2020-02-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataDictInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='标签名')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据值')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型')),
                ('sort', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='排序（升序)')),
                ('parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='父级编号')),
                ('user_id_create', models.BigIntegerField(blank=True, null=True, verbose_name='创建用户id')),
                ('create_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '数据字典表',
                'verbose_name_plural': '数据字典表',
            },
        ),
        migrations.CreateModel(
            name='domainNameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('unit_id', models.IntegerField(blank=True, null=True, verbose_name='单位ID')),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称')),
                ('dept_id', models.IntegerField(blank=True, null=True, verbose_name='部门ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门名称')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('user_id_create', models.BigIntegerField(blank=True, null=True, verbose_name='创建用户id')),
                ('create_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '停用'), (1, '正常'), (2, '故障')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '域名表',
                'verbose_name_plural': '域名表',
            },
        ),
        migrations.CreateModel(
            name='domainNameResolveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='二级域名')),
                ('unit_id', models.IntegerField(blank=True, null=True, verbose_name='单位ID')),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称')),
                ('dept_id', models.IntegerField(blank=True, null=True, verbose_name='部门ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门名称')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('user_id_create', models.BigIntegerField(blank=True, null=True, verbose_name='创建用户id')),
                ('create_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '停用'), (1, '正常'), (2, '故障')], default=1, verbose_name='状态')),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.domainNameInfo', verbose_name='域名')),
            ],
            options={
                'verbose_name': '域名解析表',
                'verbose_name_plural': '域名解析表',
            },
        ),
        migrations.CreateModel(
            name='portToPortInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(blank=True, null=True, verbose_name='单位ID')),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称')),
                ('dept_id', models.IntegerField(blank=True, null=True, verbose_name='部门ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门名称')),
                ('ip_out', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网 IP')),
                ('port_out', models.IntegerField(blank=True, null=True, verbose_name='外网端口')),
                ('ip_in', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网 IP')),
                ('port_in', models.IntegerField(blank=True, null=True, verbose_name='内网端口')),
                ('use', models.CharField(blank=True, max_length=20, null=True, verbose_name='用途')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('user_id_create', models.BigIntegerField(blank=True, null=True, verbose_name='创建用户id')),
                ('create_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_user', models.CharField(blank=True, max_length=45, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '停用'), (1, '正常'), (2, '故障')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '端口映射表',
                'verbose_name_plural': '端口映射表',
            },
        ),
    ]
