# Generated by Django 2.0.6 on 2019-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectContentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.BigIntegerField(blank=True, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门名称')),
                ('unit_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户名称')),
                ('task_name', models.CharField(max_length=45, verbose_name='任务名称')),
                ('task_type', models.IntegerField(verbose_name='任务类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('update_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='更新者')),
                ('create_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='创建用户')),
                ('comment', models.CharField(blank=True, max_length=10, null=True, verbose_name='备注')),
                ('type1', models.IntegerField(blank=True, null=True, verbose_name='执行模式')),
                ('type2', models.IntegerField(blank=True, null=True, verbose_name='设备分类2')),
                ('type3', models.IntegerField(blank=True, null=True, verbose_name='设备分类3')),
                ('name1', models.CharField(blank=True, max_length=25, null=True, verbose_name='名称1')),
                ('name2', models.CharField(blank=True, max_length=25, null=True, verbose_name='名称2')),
                ('name3', models.CharField(blank=True, max_length=25, null=True, verbose_name='名称3')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务',
            },
        ),
        migrations.CreateModel(
            name='InspectDevInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='平台ID')),
                ('dept_id', models.BigIntegerField(blank=True, null=True, verbose_name='部门ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门名称')),
                ('unit_id', models.BigIntegerField(blank=True, null=True, verbose_name='部门ID')),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称')),
                ('unit_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='单位地址')),
                ('dev_id', models.CharField(max_length=255, unique=True, verbose_name='设备ID')),
                ('dev_name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('dev_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='巡检设备类型')),
                ('dev_status', models.IntegerField(default=1, verbose_name='设备状态')),
                ('install_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='安装位置')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('update_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新者')),
                ('create_user', models.IntegerField(verbose_name='创建用户')),
                ('create_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户手机号')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('msg_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='信息ID')),
                ('dev_image1', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备图片')),
                ('dev_image2', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备图片')),
                ('dev_image3', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备图片')),
                ('type1', models.IntegerField(blank=True, null=True, verbose_name='设备分类1')),
                ('type2', models.IntegerField(blank=True, null=True, verbose_name='设备分类2')),
                ('type3', models.IntegerField(blank=True, null=True, verbose_name='设备分类3')),
                ('last_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='最后修改者ID')),
                ('last_user_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='最后修改者名字')),
                ('last_task_id', models.BigIntegerField(blank=True, null=True, verbose_name='最后任务ID')),
                ('last_task_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='最后任务no')),
                ('last_task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='最后任务名称')),
                ('last_task_time', models.DateTimeField(blank=True, null=True, verbose_name='最后任务时间')),
                ('prev_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='之前修改者ID')),
                ('prev_user_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='之前修改者名字')),
                ('prev_task_id', models.BigIntegerField(blank=True, null=True, verbose_name='之前任务ID')),
                ('prev_task_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='之前任务no')),
                ('prev_task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='之前任务名称')),
                ('prev_task_time', models.DateTimeField(blank=True, null=True, verbose_name='之前任务时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '巡检设备',
                'verbose_name_plural': '巡检设备',
            },
        ),
    ]
