# Generated by Django 2.0.6 on 2019-04-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_inspect', '0005_inspectcontentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectcontentinfo',
            name='content_no',
        ),
    ]
