# Generated by Django 2.0.6 on 2019-06-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhihulist',
            name='hot',
            field=models.CharField(max_length=255, verbose_name='问题热度'),
        ),
        migrations.AlterField(
            model_name='zhihulist',
            name='question',
            field=models.CharField(max_length=255, verbose_name='问题标题'),
        ),
    ]
