# Generated by Django 2.0.6 on 2019-12-04 21:18

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191203_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
