# Generated by Django 2.0.6 on 2019-12-13 20:27

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='user_id_create',
            field=BigIntegerField(blank=True, null=True, verbose_name='创建用户id'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='user_id_create',
            field=BigIntegerField(blank=True, null=True, verbose_name='创建用户id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=PositiveSmallIntegerField(blank=True, choices=[(0, '后台开发者'), (1, '超级管理员'), (2, '平台管理员'), (3, '单位管理员'), (4, '部门管理员'), (5, '一般用户')], null=True, verbose_name='角色'),
        ),
    ]
