# Generated by Django 2.0.6 on 2019-12-13 20:29

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191213_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='create_time',
            field=DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='create_user',
            field=CharField(blank=True, max_length=45, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='create_time',
            field=DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='create_user',
            field=CharField(blank=True, max_length=45, null=True, verbose_name='创建者'),
        ),
    ]
