# Generated by Django 2.0.6 on 2019-12-13 20:33

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191213_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='name',
            field=CharField(max_length=30, unique=True, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='name',
            field=CharField(max_length=20, unique=True, verbose_name='部门名称'),
        ),
    ]
