# Generated by Django 2.0.6 on 2019-12-17 23:01

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191213_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdepartment',
            name='unit_name',
            field=CharField(blank=True, max_length=30, null=True, verbose_name='所属单位'),
        ),
    ]
