# Generated by Django 2.0.6 on 2020-02-19 22:00

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191219_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identifier',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=CharField(max_length=100, unique=True, verbose_name='登录账号'),
        ),
    ]
