# Generated by Django 2.0.6 on 2019-06-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190603_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id_create',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='创建用户id'),
        ),
    ]
