# Generated by Django 2.0.6 on 2020-02-19 22:50

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200219_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
