# Generated by Django 2.0.6 on 2020-02-20 12:41

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='add_time',
            field=DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='address',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='登录地区'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='agent',
            field=CharField(blank=True, max_length=200, null=True, verbose_name='客户端'),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='ip',
            field=GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
    ]
