# Generated by Django 2.0.6 on 2020-02-20 20:07

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200220_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailVirificationCode',
        ),
    ]
