# Generated by Django 2.0.6 on 2020-02-21 20:04

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200221_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogininfo',
            name='dept_id',
            field=IntegerField(blank=True, null=True, verbose_name='部门ID'),
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='dept_name',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='部门名称'),
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='unit_id',
            field=IntegerField(blank=True, null=True, verbose_name='单位ID'),
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='unit_name',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='单位名称'),
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='user_name',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='用户姓名'),
        ),
    ]
