# Generated by Django 2.0.6 on 2018-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.PositiveSmallIntegerField(choices=[(1, '主机管理'), (2, '用户管理'), (3, '用户认证'), (4, '文档管理')], verbose_name='归属')),
                ('operation', models.PositiveSmallIntegerField(choices=[(1, '添加'), (2, '修改'), (3, '启用'), (4, '停用'), (5, '登录'), (6, '退出')], verbose_name='操作')),
                ('op_num', models.IntegerField(verbose_name='被操作项目ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作详情')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '公开'), (2, '不公开')], verbose_name='公开程度')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户操作表',
                'verbose_name_plural': '用户操作表',
            },
        ),
    ]
