# Generated by Django 2.0.6 on 2019-08-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation_record', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperationrecord',
            name='op_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_op_record_user', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
    ]
