# Generated by Django 2.0.6 on 2020-02-21 20:27

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_record', '0002_auto_20200220_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperationrecord',
            name='dept_id',
            field=IntegerField(blank=True, null=True, verbose_name='部门ID'),
        ),
        migrations.AddField(
            model_name='useroperationrecord',
            name='dept_name',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='部门名称'),
        ),
        migrations.AddField(
            model_name='useroperationrecord',
            name='role',
            field=IntegerField(default=10, verbose_name='用户角色'),
        ),
        migrations.AddField(
            model_name='useroperationrecord',
            name='unit_id',
            field=IntegerField(blank=True, null=True, verbose_name='单位ID'),
        ),
        migrations.AddField(
            model_name='useroperationrecord',
            name='unit_name',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='单位名称'),
        ),
        migrations.AddField(
            model_name='useroperationrecord',
            name='user_name',
            field=CharField(blank=True, max_length=100, null=True, verbose_name='用户姓名'),
        ),
        migrations.AddField(
            model_name='useroperationrecord',
            name='username',
            field=CharField(default=1, max_length=200, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
