# Generated by Django 2.0.6 on 2020-02-21 21:04

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_record', '0003_auto_20200221_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroperationrecord',
            old_name='op_user',
            new_name='user',
        ),
    ]
