# Generated by Django 2.0.6 on 2019-08-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='document_management.DocumentTags', verbose_name='分类标签'),
        ),
        migrations.AddField(
            model_name='document',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
