# Generated by Django 2.0.6 on 2019-08-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='useinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='op_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_op_user', to=settings.AUTH_USER_MODEL, verbose_name='运维人员'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='porttoportinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='porttoportinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='operatingsysteminfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='operatingsysteminfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='hostserviceinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='hostserviceinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_management.HostInfo', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='hostserviceinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host_management.ProjectInfo', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host_management.OperatingSystemInfo', verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_update_user', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host_management.UseInfo', verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='domainnameresolveinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_res_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='domainnameresolveinfo',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_management.DomainNameInfo', verbose_name='域名'),
        ),
        migrations.AddField(
            model_name='domainnameresolveinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_res_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='domainnameinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='domainnameinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dom_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_db', to='host_management.DatabaseInfo', verbose_name='数据库'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='grant_db',
            field=models.ManyToManyField(to='host_management.DatabaseDBInfo', verbose_name='授权库'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_host', to='host_management.HostInfo', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='databasedbinfo',
            name='add_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_db_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='databasedbinfo',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_db_db', to='host_management.DatabaseInfo', verbose_name='数据库'),
        ),
    ]
