# Generated by Django 2.0.6 on 2019-11-12 19:08

from django.db.models import Model,CharField,PositiveIntegerField,DateTimeField,IntegerField,ForeignKey,BooleanField,\
    PositiveSmallIntegerField,GenericIPAddressField,DecimalField,BigIntegerField,CASCADE,ManyToManyField,FloatField
from django.db import migrations,models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', CharField(max_length=255, verbose_name='产品ID')),
                ('id_status', IntegerField(verbose_name='ID状态')),
                ('add_time', DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_user', CharField(blank=True, max_length=100, null=True, verbose_name='修改人')),
                ('update_time', DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('status', PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
    ]
